### ISSUE TITLE
Crashes on latest atmosphere at launch

### ISSUE THREAD

**Issue by JonJaded** [VelocityRa/powder-nx#1]
Hey there, I was wondering if it would be possible to compile on the latest libnx, nice fun game to play on the side.

**Comment by Electric1447** [comment]
recompiled
[powder-nx.zip](https://github.com/VelocityRa/powder-nx/files/6623374/powder-nx.zip)

**Comment by JonJaded** [comment]
Thanks again!

**Comment by P3NG00** [comment]
> recompiled [powder-nx.zip](https://github.com/VelocityRa/powder-nx/files/6623374/powder-nx.zip)

Can you please add this as a release? I couldn't get the release version to work a while back. After looking at this repo again today I saw this recompiled version and it works great. Thank you for making this. I just want more people to be able to find it.
